apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3003"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: db-service
          image: db-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db-service
  ports:
    - port: 3003
      targetPort: 3003
